### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by AkshitaJain2709** [VIB-PSB/i-ADHoRe#5]
Hi everyone, could you please help me with an i-adhore script for bash, to infer synteny for circos plots. Thanks in advance for your help

**Comment by bedroesb** [comment]
Please state the exact problem you are having in the title and make an extensive description of how you wanted to run the script, which operating system you are using and what the inputs are and what you expected to have as an outcome. 

This way the issue and response can be used by others if they come across the same problem. 

Thank you
