### ISSUE TITLE
problem installing i-adhore 3.0.01

### ISSUE THREAD

**Issue by MCH74** [VIB-PSB/i-ADHoRe#9]
Hi,
CMake runs without errors or warnings but Make throws the following errors:

[ 57%] Linking CXX executable i-adhore
/usr/bin/ld: CMakeFiles/i-adhore.dir/higherLevel.cpp.o: in function `void std::deque<Multiplicon*, std::allocator<Multiplicon*> >::_M_push_front_aux<Multiplicon* const&>(Multiplicon* const&)':
higherLevel.cpp:(.text._ZNSt5dequeIP11MultipliconSaIS1_EE17_M_push_front_auxIJRKS1_EEEvDpOT_[_ZNSt5dequeIP11MultipliconSaIS1_EE17_M_push_front_auxIJRKS1_EEEvDpOT_]+0x22f): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: CMakeFiles/i-adhore.dir/AlignmentDrawer.cpp.o: in function `AlignmentDrawer::AlignmentDrawer(Profile const*)':
AlignmentDrawer.cpp:(.text+0xbb6): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: CMakeFiles/i-adhore.dir/AlignmentDrawer.cpp.o: in function `AlignmentDrawer::AlignmentDrawer(std::vector<GeneList*, std::allocator<GeneList*> > const&)':
AlignmentDrawer.cpp:(.text+0xcd6): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: CMakeFiles/i-adhore.dir/parallel.cpp.o: in function `ParToolBox::statPartWorklSort(std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned int, std::vector<unsigned int, std::allocator<unsigned int> >&, std::vector<unsigned long, std::allocator<unsigned long> >&, std::vector<unsigned int, std::allocator<unsigned int> >&, std::vector<unsigned long, std::allocator<unsigned long> >&, std::map<unsigned long, unsigned int, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, unsigned int> > >&)':
parallel.cpp:(.text+0xbe9): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: CMakeFiles/i-adhore.dir/DataSet.cpp.o: in function `DataSet::printProfiles()':
DataSet.cpp:(.text+0x8618): undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: CMakeFiles/i-adhore.dir/GHM.cpp.o:GHM.cpp:(.text+0x35d4): more undefined references to `std::__throw_bad_array_new_length()' follow
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/i-adhore.dir/build.make:471: src/i-adhore] Error 1
make[1]: *** [CMakeFiles/Makefile2:172: src/CMakeFiles/i-adhore.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

I am using cmake version 3.25.1, make v4.3 and gcc v11.4.0

Thanks,
Mark

**Comment by bedroesb** [comment]
@MCH74 hey! Could you resolve the problem?

**Comment by bedroesb** [comment]
ok great to hear, thanks for letting us know.
